export default '<table>\n'
  + '      <thead>\n'
  + '        <tr>\n'
  + '          <th>Раунд</th>\n'
  + '          <th>Кол-во игр</th>\n'
  + '          <th>Кол-во игроков</th>\n'
  + '          <th>День недели</th>\n'
  + '        </tr>\n'
  + '      </thead>\n'
  + '      <tr>\n'
  + '        <td data-th="Раунд">1</td>\n'
  + '        <td data-th="Кол-во игр">Adventure, Sci-fi</td>\n'
  + '        <td data-th="Кол-во игроков">1977</td>\n'
  + '        <td data-th="День недели">$460,935,665</td>\n'
  + '      </tr>\n'
  + '      <tr>\n'
  + '        <td data-th="Раунд">222</td>\n'
  + '        <td data-th="Кол-во игр">Comedy</td>\n'
  + '        <td data-th="Кол-во игроков">1986</td>\n'
  + '        <td data-th="День недели">$16,295,774</td>\n'
  + '      </tr>\n'
  + '      <tr>\n'
  + '        <td data-th="Раунд">American Graffiti</td>\n'
  + '        <td data-th="Кол-во игр">Comedy, Drama</td>\n'
  + '        <td data-th="Кол-во игроков">1973</td>\n'
  + '        <td data-th="День недели">Пятница</td>\n'
  + '      </tr>\n'
  + '    </table>'
