export const NOT_AVAILABLE = 'N/A'

export const defaultStatistic = {
  // CSGO
  assistantsPerRound: NOT_AVAILABLE,
  deathPerRound: NOT_AVAILABLE,
  headshots: NOT_AVAILABLE,
  kDRatio: NOT_AVAILABLE,
  killsPerRound: NOT_AVAILABLE,
  mapsPlayed: NOT_AVAILABLE,
  matchPlayed: 0,
  recentResults: NOT_AVAILABLE,
  roundsPlayed: NOT_AVAILABLE,
  totalAssists: NOT_AVAILABLE,
  totalDeath: NOT_AVAILABLE,
  totalKills: NOT_AVAILABLE,
  winrate: NOT_AVAILABLE,
  // DOTA2
  matchCount: 0,
  winCount: 0,
  lossCount: 0,
  avgDuration: NOT_AVAILABLE,
  avgKills: 0,
  maxKills: 0,
  avgDeath: 0,
  maxDeath: 0,
  avgAssists: 0,
  maxAssists: 0,
  kda: NOT_AVAILABLE,
  avgLastHits: 0,
  maxLastHits: 0,
  avgDenies: 0,
  maxDenies: 0,
  maxGold: 0,
  avgGold: 0,
  avgXp: 0,
  maxXp: 0,
  heroDamage: 0,
  towerDamage: 0,
  healing: 0,
}
