export const MATCH_STATUSES = {
  PAUSE: 'PAUSE',
  CANCELED: 'CANCELED',
  CHECK_IN: 'CHECK_IN',
  VOTING: 'VOTING',
  SETUP_SERVER: 'SETUP_SERVER',
  ONGOING: 'ONGOING',
  DECLINE: 'DECLINE',
  FINISHED: 'FINISHED',
  TECHNICAL_DEFEAT: 'TECHNICAL_DEFEAT',
}

export const MATCH_ENDED_STATUSES = [
  MATCH_STATUSES.CANCELED,
  MATCH_STATUSES.FINISHED,
  MATCH_STATUSES.TECHNICAL_DEFEAT,
]
