export const TRIGGER_LOGIN_MODAL_VISIBILITY = 'LOGIN/TRIGGER_VISIBILITY'

export const OPEN_LOGIN_MODAL_VISIBILITY = 'LOGIN/OPEN'

export const TRIGGER_FORGOT_PASS_MODAL_VISIBILITY = 'FORGOT_PASS/TRIGGER_VISIBILITY'

export const TRIGGER_SIGN_UP_MODAL_VISIBILITY = 'SIGN_UP_MAGIC_LINK/TRIGGER_VISIBILITY'

export const SET_TEMPORARY_USER_EMAIL = 'SET_TEMPORARY_USER_EMAIL'

export const TRIGGER_PROMOCODES_MODAL_VISIBILITY = 'PROMOCODES/TRIGGER_VISIBILITY'

export const TRIGGER_CHANGE_EMAIL_MODAL_VISIBILITY = 'CHANGE_EMAIL/TRIGGER_VISIBILITY'

export const TRIGGER_MUTUAL_MODAL_VISIBILITY = 'MUTUAL_MODAL/TRIGGER_VISIBILITY'
