const socialLinks = {
  pages: {
    en: [
      {
        id: 0,
        type: 'facebook',
        title: 'Facebook',
        description: 'The main stage for a big esports news',
        url: 'https://www.facebook.com/WePlayEsport',
      },
      {
        id: 1,
        type: 'twitter',
        title: 'Twitter',
        description: '"What\'s going on" in brief',
        url: 'https://twitter.com/weplayesport',
      },
      {
        id: 2,
        type: 'instagram',
        title: 'Instagram',
        description: 'Esports life behind the scenes',
        url: 'https://www.instagram.com/weplay_esports',
      },
      {
        id: 3,
        type: 'discord',
        title: 'Discord',
        description: 'Discussions, chilling and chatting',
        url: 'https://discord.gg/yMKBw2s',
      },
      {
        id: 4,
        type: 'steam',
        title: 'Steam',
        description: 'Come for guides and contests',
        url: 'https://steamcommunity.com/groups/weplay_esports',
      },
    ],
    ru: [
      {
        id: 1,
        type: 'facebook',
        title: 'Facebook',
        description: 'Главные новости мира гейминга',
        url: 'https://www.facebook.com/yeswegomedia',
      },
      {
        id: 2,
        type: 'twitter',
        title: 'Twitter',
        description: 'Когда нет времени читать много',
        url: 'https://twitter.com/weplay_esports',
      },
      {
        id: 3,
        type: 'telegramMedia',
        title: 'Telegram',
        description: 'Всё по теме в одном канале',
        url: 'https://t.me/joinchat/AAAAAFJqK4ZPLUVIg5xKog',
      },
      // {
      //   id: 4,
      //   type: 'vk',
      //   title: 'Vkontakte',
      //   description: 'Наше ламповое комьюнити',
      //   url: 'NEED TO SET URL!',
      // },
      {
        id: 5,
        type: 'instagram',
        title: 'Instagram',
        description: 'Показываем всё, что обычно скрыто',
        url: 'https://www.instagram.com/weplay_esports',
      },
      {
        id: 6,
        type: 'discord',
        title: 'Discord',
        description: 'Общаемся про киберспорт и не только',
        url: 'https://discord.gg/CFX9TnX',
      },
      {
        id: 7,
        type: 'zenMedia',
        title: 'Zen',
        description: 'Лучшие статьи редакции',
        url: 'https://zen.yandex.ru/id/5c41dc716a175700ae7c6c2a',
      },
      {
        id: 8,
        type: 'steam',
        title: 'Steam',
        description: 'Читаем гайды и участвуем в конкурсах',
        url: 'https://steamcommunity.com/groups/weplay_esports',
      },
    ],
  },
  videos: {
    en: [
      {
        id: 0,
        type: 'youtube',
        title: 'WePlay! Esports',
        description: 'Highlights, interview and more',
        url: 'https://www.youtube.com/channel/UCBiFae7FtktcnHAwmgUTOIg',
      },
      {
        id: 1,
        type: 'youtube',
        title: 'WePlay! Dota 2',
        description: 'The best videos of Dota 2 WePlay! tournaments',
        url: 'https://www.youtube.com/channel/UCB1Cp_eNvUGWoIt4K0ZGDDg',
      },
      {
        id: 2,
        type: 'youtube',
        title: 'WePlay! CS:GO',
        description: 'The Top videos of CS:GO WePlay! tournaments',
        url: 'https://www.youtube.com/channel/UC7fnl0dTMEHnJQ-55CmzTbQ',
      },
      {
        id: 3,
        type: 'youtube',
        title: 'WePlay! Artifact',
        description: 'The best videos of Artifact WePlay! tournaments',
        url: 'https://www.youtube.com/channel/UCSBZ5amOqJeLsqY2zbG-yDg',
      },
      {
        id: 4,
        type: 'twitch',
        title: 'WePlay! Twitch EN',
        description: 'All WePlay! events are here',
        url: 'https://www.twitch.tv/weplayesport_en',
      },
    ],
    ru: [
      {
        id: 0,
        type: 'youtube',
        title: 'WePlay! Esports',
        description: 'Хайлайты, интервью и многое другое',
        url: 'https://www.youtube.com/channel/UCBiFae7FtktcnHAwmgUTOIg',
      },
      {
        id: 1,
        type: 'youtube',
        title: 'WePlay! Dota 2',
        description: 'Лучшее из WePlay! турниров по Dota 2',
        url: 'https://www.youtube.com/channel/UCB1Cp_eNvUGWoIt4K0ZGDDg',
      },
      {
        id: 2,
        type: 'youtube',
        title: 'WePlay! CS:GO',
        description: 'Хайлайты WePlay! турниров по CS:GO',
        url: 'https://www.youtube.com/channel/UC7fnl0dTMEHnJQ-55CmzTbQ',
      },
      {
        id: 3,
        type: 'youtube',
        title: 'WePlay! Artifact',
        description: 'Лучшее из WePlay! турниров по Artifact',
        url: 'https://www.youtube.com/channel/UCSBZ5amOqJeLsqY2zbG-yDg',
      },
      {
        id: 4,
        type: 'twitch',
        title: 'WePlay! Twitch RU',
        description: 'Стрим всех WePlay! ивентов',
        url: 'https://www.twitch.tv/weplayesport_ru',
      },
      {
        id: 5,
        type: 'twitch',
        title: 'WePlay! Twitch EN',
        description: 'Cтримим здесь на английском',
        url: 'https://www.twitch.tv/weplayesport_en',
      },
    ],
  },
}
export const getSocialLinks = (language, dataKey) => socialLinks[dataKey][language]
