export const ARTIFACT_STRENGTH = 'ARTIFACT_STRENGTH'
export const ARTIFACT_AGILITY = 'ARTIFACT_AGILITY'
export const ARTIFACT_INTELLIGENCE = 'ARTIFACT_INTELLIGENCE'
export const ARTIFACT_PROMO_STRENGTH = 'ARTIFACT_PROMO_STRENGTH'
export const ARTIFACT_PROMO_AGILITY = 'ARTIFACT_PROMO_AGILITY'
export const ARTIFACT_PROMO_INTELLIGENCE = 'ARTIFACT_PROMO_INTELLIGENCE'

export const ARTIFACT_STAGE_REGISTRATION = {
  1: {
    registrationSource: ARTIFACT_STRENGTH,
    registrationPromoSource: ARTIFACT_PROMO_STRENGTH,
  },
  2: {
    registrationSource: ARTIFACT_AGILITY,
    registrationPromoSource: ARTIFACT_PROMO_AGILITY,
  },
  3: {
    registrationSource: ARTIFACT_INTELLIGENCE,
    registrationPromoSource: ARTIFACT_PROMO_INTELLIGENCE,
  },
}
