export const ERROR_NOTIFICATION_TYPE = 'error'
export const INVITE_NOTIFICATION_TYPE = 'invite'
export const DEFAULT_NOTIFICATION_TYPES = [ERROR_NOTIFICATION_TYPE]
export const DEFAULT_NOTIFICATION_DURATION = 10000
