import { ESPORTS_BANNERS_IDS } from 'config/banners'

export const BANNERS_FOR_SERVICES = {
  NATIVE_INTEGRATION: ESPORTS_BANNERS_IDS,
  SPONSORSHIP: ESPORTS_BANNERS_IDS,
  PR_SMM: ESPORTS_BANNERS_IDS,
  TALK_SHOWS: ESPORTS_BANNERS_IDS,
  TOURNAMENT_INTEGRATION: ESPORTS_BANNERS_IDS,
  BROADCASTING_RIGHTS: ESPORTS_BANNERS_IDS,
  VOD_RIGHTS: ESPORTS_BANNERS_IDS,
  TALK_SHOWS_RIGHTS: ESPORTS_BANNERS_IDS,
}
